/**
 * Represents the structure of an image generated by the AI
 * and stored in the database.
 */
export interface GeneratedImage {
  id: string; // UUID
  user_id: string;
  community_id: string;
  storage_url: string;
  prompt_structured: Record<string, unknown>; // Changed any to unknown
  is_public: boolean;
  created_at: string; // Timestamptz - usually serialized as ISO 8601 string
} 